### PR TITLE
expand macros in JSExpr instead of current_module()

### LINKED ISSUE #13: Issues with macro expansion in `jsexpr`
This is the root cause of https://github.com/JunoLab/Blink.jl/issues/134

For a simple example, try: 

```julia
julia> module Foo
         import JSExpr: @new, jsexpr
         f() = jsexpr(:(@new Int(1)))
       end
WARNING: replacing module Foo
Foo

julia> Foo.f()
ERROR: JSExpr: Unsupported `error` expression, $(Expr(:error, UndefVarError(Symbol("@new"))))
Stacktrace:
 [1] macro expansion at /home/rdeits/Downloads/blink-bug/packages/v0.6/JSExpr/src/JSExpr.jl:191 [inlined]
 [2] macro expansion at /home/rdeits/Downloads/blink-bug/packages/v0.6/MacroTools/src/macro.jl:18 [inlined]
 [3] jsexpr(::Expr) at /home/rdeits/Downloads/blink-bug/packages/v0.6/JSExpr/src/JSExpr.jl:159
 [4] macro expansion at /home/rdeits/Downloads/blink-bug/packages/v0.6/JSExpr/src/JSExpr.jl:179 [inlined]
 [5] macro expansion at /home/rdeits/Downloads/blink-bug/packages/v0.6/MacroTools/src/macro.jl:18 [inlined]
 [6] jsexpr(::Expr) at /home/rdeits/Downloads/blink-bug/packages/v0.6/JSExpr/src/JSExpr.jl:159
 [7] f() at ./REPL[12]:3
```

The issue is that https://github.com/JuliaGizmos/JSExpr.jl/blob/14949342ac3e15d6f8bd05621960997ce2e412d3/src/JSExpr.jl#L179 tries to expand the `@new` macro in `current_module()`, which in this case doesn't know what that macro is. 

I think it would be safer to do `macroexpand(JSExpr, x)` instead, as we know that's where the correct version of `@new`, `@var`, etc. live.

### PR DESCRIPTION
**Pull request by rdeits**
Fixes #13 
Fixes https://github.com/JunoLab/Blink.jl/issues/134

Does this seem like a reasonable thing to do?

### CODE REVIEW

**Comment by tkoolen** [comment]
Friendly bump 🙂.

**Comment by shashi** [comment]
Seems reasonable... Downside is you can't use macros defined outside the module, but I haven't seen anyone wanting to do that yet.

**Comment by rdeits** [comment]
I'm concerned this may have been a mistake. With this change, any package using the regular `@js` macro throws warnings while precompiling: https://github.com/rdeits/MeshCat.jl/issues/52

I'm afraid we might have to revert this and just modify Blink.jl to work around https://github.com/JunoLab/Blink.jl/issues/134

Sorry :slightly_frowning_face:

**Comment by shashi** [comment]
No worries! Thanks for trailing this.

**Pull request merged**
